
services:
  frontend:
    image: node:18
    container_name: linkspy-frontend
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
    networks:
      - linkspy

  nginx:
    image: nginx:latest
    container_name: linkspy-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
    networks:
      - linkspy

networks:
  linkspy:
    driver: bridge
